### ISSUE TITLE
机器学习和数据有道的第一章1.2都有个错误

### ISSUE THREAD

**Issue by SuperShook** [Visualize-ML/Book6_First-Course-in-Data-Science#1]
哪本书讲的是分类算法，
哪本书讲的是聚类算法？
![image](https://user-images.githubusercontent.com/40540798/219664480-d370d50d-e9f5-4233-b569-eca4c0f190b7.png)

**Comment by Visualize-ML** [comment]
《机器学习》中大篇幅讲解：分类、聚类
《数据有道》专门讲解：回归、降维
