### ISSUE TITLE
Book6_Ch01_万物皆数

### ISSUE THREAD

**Issue by zmcmcc** [Visualize-ML/Book6_First-Course-in-Data-Science#13]
page8 “如图 8 所示，无监督学习主要分为绍聚类 (clustering)、降维 (dimensionality reduction)。”  "绍"字是否多余？

**Comment by zmcmcc** [comment]
看到issue里已经有其他人提过相同问题了

**Comment by Visualize-ML** [comment]
谢谢你！这些问题将会在明年统一修改。
