### ISSUE TITLE
ch11代码注释错误

### ISSUE THREAD

**Issue by YunLzzz** [Visualize-ML/Book6_First-Course-in-Data-Science#19]
这里标的是Bk6_Ch14_02.ipynb,应该是Bk6_Ch11_02.ipynb
<img width="441" alt="屏幕截图 2024-10-15 130229" src="https://github.com/user-attachments/assets/2c42f69c-73fd-454f-b62e-ad178229dab1">

**Comment by Visualize-ML** [comment]
谢谢你，这部分没有自动编号。请继续批评指正。
