### ISSUE TITLE
Book6_Ch09_Page23_ConditionNumber

### ISSUE THREAD

**Issue by Hurricane-k** [Visualize-ML/Book6_First-Course-in-Data-Science#3]
9.16条件数：多重共线中
想请问，Eq.(57)下面提到条件数小于30，可以不必担心多重共线性。这个结论出自哪里，是您研究得出的结论还是有哪些参考文献，能否标明一下，能否解释一下

**Comment by Visualize-ML** [comment]
谢谢来信！我会加上参考文献，请多多批评。
